defmodule Fumetsu.Entity.Constants do
  import Bitwise

  @rest_error_codes %{
    0      => :general_error,
    10001  => :unknown_account,
    10002  => :unknown_application,
    10003  => :unknown_channel,
    10004  => :unknown_guild,
    10005  => :unknown_integration,
    10006  => :unknown_invite,
    10007  => :unknown_member,
    10008  => :unknown_message,
    10009  => :unknown_permission_overwrite,
    10010  => :unknown_provider,
    10011  => :unknown_role,
    10012  => :unknown_token,
    10013  => :unknown_user,
    10014  => :unknown_emoji,
    10015  => :unknown_webhook,
    10026  => :unknown_ban,
    10027  => :unknown_sku,
    10028  => :unknown_store_listing,
    10029  => :unknown_entitlement,
    10030  => :unknown_build,
    10031  => :unknown_lobby,
    10032  => :unknown_branch,
    10036  => :unknown_redistributable,
    10057  => :unknown_guild_template,
    10063  => :unknown_application_command,
    20001  => :bots_cannot_use_this_endpoint,
    20002  => :only_bots_can_use_this_endpoint,
    20022  => :announcement_edit_limit_exceeded,
    20028  => :channel_send_rate_limit,
    30001  => :maximum_number_of_guilds_reached,
    30002  => :maximum_number_of_friends_reached,
    30003  => :maximum_number_of_pins_reached_for_the_channel,
    30005  => :maximum_number_of_guild_roles_reached,
    30007  => :maximum_number_of_webhooks_reached,
    30010  => :maximum_number_of_reactions_reached,
    30013  => :maximum_number_of_guild_channels_reached,
    30015  => :maximum_number_of_attachments_in_a_message_reached,
    30016  => :maximum_number_of_invites_reached,
    30031  => :guild_already_has_template,
    40001  => :unauthorized,
    40002  => :verify_your_account,
    40005  => :request_entity_too_large,
    40006  => :feature_temporarily_disabled_server_side,
    40007  => :user_banned_from_this_guild,
    40033  => :this_message_was_already_crossposted,
    50001  => :missing_access,
    50002  => :invalid_account_type,
    50003  => :cannot_execute_action_on_dm_channel,
    50004  => :guild_widget_disabled,
    50005  => :cannot_edit_message_authored_by_another_user,
    50006  => :cannot_send_an_empty_message,
    50007  => :cannot_send_messages_to_this_user,
    50008  => :cannot_send_messages_in_voice_channel,
    50009  => :channel_verification_level_too_high_for_you_to_gain_access,
    50010  => :oauth2_application_does_not_have_bot,
    50011  => :oauth2_application_limit_reached,
    50012  => :invalid_oauth2_state,
    50013  => :missing_permissions,
    50014  => :invalid_token,
    50015  => :note_was_too_long,
    50016  => :provided_too_few_or_too_many_messages_to_delete,
    50019  => :message_can_only_be_pinned_in_the_channel_it_was_sent_in,
    50020  => :invite_code_invalid_or_taken,
    10021  => :cannot_execute_action_on_system_message,
    50024  => :cannot_execute_action_on_this_channel_type,
    50025  => :invalid_oauth2_access_token,
    50027  => :invalid_webhook_token,
    50033  => :invalid_recipients,
    50034  => :one_of_the_messages_provided_was_too_old_for_bulk_delete,
    50035  => :invalid_form_body_or_content_type,
    50036  => :invite_accepted_to_guild_without_the_bot_being_in,
    50041  => :invalid_api_version,
    50074  => :cannot_delete_channel_required_for_community_guilds,
    50081  => :invalid_sticker_sent,
    60003  => :two_factor_authentication_is_required,
    90001  => :reaction_was_blocked,
    130000 => :api_resource_overloaded,
  }

  @intents %{
    1 <<< 0 => :guilds,
    1 <<< 1 => :guild_members,
    1 <<< 2 => :guild_bans,
    1 <<< 3 => :guild_emojis,
    1 <<< 4 => :guild_integrations,
    1 <<< 5 => :guild_webhooks,
    1 <<< 6 => :guild_invites,
    1 <<< 7 => :guild_voice_states,
    1 <<< 8 => :guild_presences,
    1 <<< 9 => :guild_messages,
    1 <<< 10 => :guild_message_reactions,
    1 <<< 11 => :guild_message_typing,
    1 <<< 12 => :direct_messages,
    1 <<< 13 => :direct_message_reactions,
    1 <<< 14 => :direct_message_typing,
  }

  @permissions %{
    1 <<< 0 => :create_instant_invite,
    1 <<< 1 => :kick_members,
    1 <<< 2 => :ban_members,
    1 <<< 3 => :administrator,
    1 <<< 4 => :manage_channels,
    1 <<< 5 => :manage_guild,
    1 <<< 6 => :add_reactions,
    1 <<< 7 => :view_audit_log,
    1 <<< 8 => :priority_speaker,
    1 <<< 9 => :stream,
    1 <<< 10 => :view_channel,
    1 <<< 11 => :send_messages,
    1 <<< 12 => :send_tts_messages,
    1 <<< 13 => :manage_messages,
    1 <<< 14 => :embed_links,
    1 <<< 15 => :attach_files,
    1 <<< 16 => :read_message_history,
    1 <<< 17 => :mention_everyone,
    1 <<< 18 => :use_external_emojis,
    1 <<< 19 => :view_guild_insights,
    1 <<< 20 => :connect,
    1 <<< 21 => :speak,
    1 <<< 22 => :mute_members,
    1 <<< 23 => :deafen_members,
    1 <<< 24 => :move_members,
    1 <<< 25 => :use_vad,
    1 <<< 26 => :change_nickname,
    1 <<< 27 => :manage_nicknames,
    1 <<< 28 => :manage_roles,
    1 <<< 29 => :manage_webhooks,
    1 <<< 30 => :manage_emojis,
  }

  @inv_rest_error_codes @rest_error_codes |> Enum.map(fn {k, v} -> {v, k} end) |> Map.new
  @inv_intents          @intents |> Enum.map(fn {k, v} -> {v, k} end) |> Map.new
  @inv_permissions      @permissions |> Enum.map(fn {k, v} -> {v, k} end) |> Map.new

  def rest_error_codes, do: @rest_error_codes
  def intents, do: @intents
  def permissions, do: @permissions
end
